export const CLEAR_ERRORS = "CLEAR_ERRORS";
export const GET_ERRORS = "GET_ERRORS";
export const SEND_CONTACT = "SEND_CONTACT";
export const SET_CURRENT_STUDENT = "SET_CURRENT_STUDENT";
export const SET_CURRENT_STAFF = "SET_CURRENT_STAFF";
export const GET_PROFILE = "GET_PROFILE";
